title: MMtech Blog
description: Software Engineering, Cybersecurity & Data Science
author: Mohamed Musa
email: gables.05-cannier@icloud.com

# GitHub and social media
github_username: https://github.com/MMtech-Dev
linkedin_username: https://www.linkedin.com/in/mohamed-musa-a35124286

# Build settings
theme: minima
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - SETUP_GUIDE.md
  - QUICK_START.md
  - blog_organization.md
